---

- name: Install Java 1.7
  apt: name=openjdk-7-jre-headless state=present

- name: Download Graylog2 repository package
  get_url: url={{ graylog2_packages_url }} dest=/tmp/graylog2_repository.deb

- apt: name=apt-transport-https state=installed

- name: Install Graylog2 repository
  apt: deb=/tmp/graylog2_repository.deb state=installed dpkg_options='force-all'

- apt: update_cache=yes
  ignore_errors: yes
