---

- name: Install Graylog2 server
  apt: name=graylog2-server state=present force=yes

# this probably is needed as after deployment /spool was not writable
- name: Ensure spool directory is writable
  file: path={{ message_cache_spool_dir }} state=directory owner=graylog2 group=graylog2

- name: Configure Graylog2 server
  template: src=graylog2.server.conf.j2 dest=/etc/graylog2.conf owner=graylog2 group=graylog2 mode=0644
  notify: restart graylog2-server

- name: Configure Graylog2 ES
  template: src=graylog2.server.elasticsearch.yml.j2 dest=/etc/graylog2-elasticsearch.yml owner=graylog2 group=graylog2 mode=0644
  notify: restart graylog2-server

- name: Configure Graylog2 server defaults
  template: src=graylog2.server.default.j2 dest=/etc/default/graylog2-server owner=graylog2 group=graylog2 mode=0644
  notify: restart graylog2-server
